"""Add telemetry to RecoveryAttempt

Revision ID: 3c0d3a2ee29d
Revises: faecf6256136
Create Date: 2026-09-02 15:59:44.049118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0d3a2ee29d'
down_revision: Union[str, Sequence[str], None] = 'faecf6256136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('provider_used', sa.String(), nullable=True))
    op.add_column('recovery_attempts', sa.Column('latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_attempts', 'latency_ms')
    op.drop_column('recovery_attempts', 'provider_used')
    # ### end Alembic commands ###
