"""add razorpay gateway identifiers

Revision ID: a8243fe636d8
Revises: 3c0d3a2ee29d
Create Date: 2026-09-02 21:53:05.959732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8243fe636d8'
down_revision: Union[str, Sequence[str], None] = '3c0d3a2ee29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('gateway_payment_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('gateway_refund_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_gateway_payment_id'), 'transactions', ['gateway_payment_id'], unique=True)
    op.create_index(op.f('ix_transactions_gateway_refund_id'), 'transactions', ['gateway_refund_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_gateway_refund_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_payment_id'), table_name='transactions')
    op.drop_column('transactions', 'gateway_refund_id')
    op.drop_column('transactions', 'gateway_payment_id')
    # ### end Alembic commands ###
