"""Add webhook retry fields

Revision ID: faecf6256136
Revises: 647f86570217
Create Date: 2026-08-28 15:00:34.748842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faecf6256136'
down_revision: Union[str, Sequence[str], None] = '647f86570217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('webhook_events', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'last_attempt_at')
    op.drop_column('webhook_events', 'retry_count')
    # ### end Alembic commands ###
